spring.application.name=microserviciodonacion
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/db_bibliotecaam
spring.datasource.username=root
spring.datasource.password=

# update: crea las tablas si no existen, las actualiza
# create-drop: Testeamos con esto para que la BD no guarde los datos erroneos (En caso de haberlos)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect